using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class Questions {

	public string[] question = new string[] { 
		"ALBATROSS",   
		"AUKLET",   
		"BLACKBIRD", 
		"RED-WINGED",   
		"BLUEBIRD", 
		"COWBIRD",   
		"CROW",   
		"DOVE", 
		"DOWITCHER",   
		"DUCK", 
		"EAGLE",   
		"EGRET",   
		"FALCON", 
		"GOOSE",   
		"HAWK", 
		"KIWI",   
		"CASSOWARY",   
		"PENGUIN", 
		"STEAMER DUCK",   
		"DINOSOARING", 
		"TELEVISON",   
		"FAN",   
		"SPEAKER", 
		"MOBILE PHONES",   
		"SHOES", 
		"PEN",   
		"PRINTER",   
		"TABLE", 
		"CAR",   
		"HUMMINGBIRD", 
		"KINGBIRD",   
		"KITE",   
		"OWL", 
		"PELICAN",   
		"PIGEON", 
		"PUFFIN",   
		"RAVEN",   
		"SANDPIPER", 
		"SPARROW",   
		"SWIFT", 
		"TITMOUSE",   
		"TURKEY",   
		"TRUCK", 
		"BAG",   
		"WATER", 
		"BOTTLE",   
		"GRIDDLE",   
		"AIR FRYERS", 
		"FOOD WARMERS",   
		"GARBAGE DISPOSALS", 
		"RANGES",   
		"WAFFLE IRON",   
		"HUMIDIFIERS", 
		"BACK BOILER",   
		"MOUSE TRAP", 
		"WOODPECKER",   
		"BATS",   
		"FLIGHTS", 
		"REINDEER",   
		"CHI", 
		"PLANE",   
		"HELICOPTER",   
		"HANG GLIDER", 
		"GLIDER",   
		"PTERODACTYL", 
		"PARASOUTE",   
		"FLY SQUIRREL",   
		"FLYING FROG", 
		"JET",   
		"TIE PRESS", 
		"PATIO HEATER",   
		"TROUSER PRESS",   
		"ROBOT", 
		"KETTLE",   
		"SHREDDER", 
		"CAMCORDER",   
		"RADIO RECEIVER",   
		"ROKU", 
		"NECK HAMMOCK",   
		"FORK", 
		"DOORMAT",   
		"CRYSTAL BALL",   
		"PUG PLANTER", 
		"FLYING SNAKE",   
		"FLYING FISH", 
		"DRAGON",   
		"AIRCRAFTS",   
		"DRONES", 
		"BALLONS",   
		"TIME", 
		"BLIMP",   
		"ROCKET",   
		"INSECT", 
		"BUTTERFLY",   
		"BEE", 
		"WASP",   
		"PAPER AIRPLANE",   
		"TUB DRAIN", 
		"SHAPED KNIFES",   
		"EGG CANDLE", 
		"WAFFLE MAKER",   
		"FRAME",   
		"CAPTAIN MARVEL", 
		"BOX",   
		"POTATOS", 
		"YOGA MAT",   
		"SPOUSE",   
		"CHILDREN", 
		"HOME",   
		"ROOM MATE", 
		"FRIEND",   
		"WIVES",   
		"CAP", 
		"HOT AIR BALLOON",   
		"WEATHER BALLOON", 
		"HELIUM BALLOON",   
		"AIR",   
		"BREEZE", 
		"CLOUD",   
		"CLOTHES", 
		"DUST",   
		"DRAGONFLY",   
		"SPIDERS", 
		"DRACO LIZARDS",   
		"MAMMALS", 
		"SPIDERMAN",   
		"IRON MAN",   
		"HULK", 
		"SUPER MAN",   
		"SUPER WOMEN", 
		"AQUAMAN",   
		"SPIDER MAN",   
		"WONDER WOMAN", 
		"THOR",   
		"ANTMAN", 
		"FLASH",   
		"I-ROBOT",   
		"SILVER SURFER", 
		"SHAZAM",   
		"SUPERGIRL", 
		"STARFIRE",   
		"GREEN LANTERN",   
		"SUPERBOY", 
		"ROGUE",   
		"SENTRY", 
		"CAPTAIN ATOM",   
		"MARTIAN MANHUNTER",   
		"DOCTOR FATE", 
		"HAWKMAN",   
		"STORM", 
		"MONICA RAMBEAU",   
		"CANNONBALL",   
		"BLACK CONDOR", 
		"HUMAR TORCH",   
		"MOSQUITO", 
		"FRUIT FLIES",   
		"BLACK FLY",   
		"COCKROACH", 
		"SUGAR GLINDER",   
		"STEAM", 
		"DUST", 
		"AIR", 
		"WIND", 
		"BREEZE", 
		"TENNIS BALL", 
		"BADMINTON ROCKET", 
		"FOOTBALL", 
		"FLAG", 
		"DOVE LEAF", 
		"PEICE OF PAPER",
		"FANCY PAPERS", 
		"TAIL PAPER", 
		"HAIR", 
		"KISSES", 
		"POWDER", 
		"GOAL KEEPER", 
		"SHEET", 
		"CORBAN SHEETS", 
		"BED SHEET", 
		"NEWS SHEET", 
		"KRAFT SHEET", 
		"BOGUS PAPER", 
		"TISSUE PAPER", 
		"COLOR PAPER", 
		"TRANSPARENT PAPER", 
		"GIFT PAPER", 
		"SMELL", 
		"GOOD SMELL", 
		"BAD SMELLS", 
		"THREADS", 
		"STREAMS PAPER", 
		"CREPE PAPER", 
		"DIY PAPER", 
		"BLADDER", 
		"PEPPER", 
		"BOOMRANG", 
		"SMOG", 
		"FOG", 
		"GRIDLE", 
		"REMOTE", 
		"WHEELER", 
		"IPHONE CASE", 
		"PILLOW", 
		"MOUSER TRACKER"
	};
		
}
