// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_pretty_skilled = "CgkIg7eIzcIOEAIQBA"; // <GPGSID>
        public const string achievement_unlock_twitter = "CgkIg7eIzcIOEAIQBw"; // <GPGSID>
        public const string achievement_super_ability = "CgkIg7eIzcIOEAIQGA"; // <GPGSID>
        public const string achievement_hero = "CgkIg7eIzcIOEAIQCQ"; // <GPGSID>
        public const string leaderboard_flyupanddownboard = "CgkIg7eIzcIOEAIQIQ"; // <GPGSID>
        public const string achievement_super_man = "CgkIg7eIzcIOEAIQIA"; // <GPGSID>
        public const string achievement_fabulous = "CgkIg7eIzcIOEAIQAg"; // <GPGSID>
        public const string achievement_computer_mind = "CgkIg7eIzcIOEAIQDQ"; // <GPGSID>
        public const string achievement_surprise = "CgkIg7eIzcIOEAIQBQ"; // <GPGSID>
        public const string achievement_bright_spark = "CgkIg7eIzcIOEAIQHQ"; // <GPGSID>
        public const string achievement_a_cool_reward = "CgkIg7eIzcIOEAIQAA"; // <GPGSID>
        public const string achievement_marvelous = "CgkIg7eIzcIOEAIQAw"; // <GPGSID>
        public const string achievement_talented = "CgkIg7eIzcIOEAIQEg"; // <GPGSID>
        public const string achievement_unlocked_facebook = "CgkIg7eIzcIOEAIQBg"; // <GPGSID>
        public const string achievement_alien = "CgkIg7eIzcIOEAIQCw"; // <GPGSID>
        public const string achievement_egg_head = "CgkIg7eIzcIOEAIQHA"; // <GPGSID>
        public const string achievement_master_mind = "CgkIg7eIzcIOEAIQDA"; // <GPGSID>
        public const string achievement_brilliance = "CgkIg7eIzcIOEAIQEA"; // <GPGSID>
        public const string achievement_great_ability = "CgkIg7eIzcIOEAIQDw"; // <GPGSID>
        public const string achievement_specialist = "CgkIg7eIzcIOEAIQCg"; // <GPGSID>
        public const string achievement_hungry_man = "CgkIg7eIzcIOEAIQAQ"; // <GPGSID>
        public const string achievement_magnificent_man = "CgkIg7eIzcIOEAIQCA"; // <GPGSID>
        public const string achievement_brainbox = "CgkIg7eIzcIOEAIQHw"; // <GPGSID>
        public const string achievement_expert = "CgkIg7eIzcIOEAIQFQ"; // <GPGSID>
        public const string achievement_master_giant = "CgkIg7eIzcIOEAIQGg"; // <GPGSID>
        public const string achievement_faculty_mind = "CgkIg7eIzcIOEAIQFg"; // <GPGSID>
        public const string achievement_dreamer = "CgkIg7eIzcIOEAIQDg"; // <GPGSID>
        public const string achievement_master = "CgkIg7eIzcIOEAIQGw"; // <GPGSID>
        public const string achievement_brainy = "CgkIg7eIzcIOEAIQEw"; // <GPGSID>
        public const string achievement_power = "CgkIg7eIzcIOEAIQFw"; // <GPGSID>
        public const string achievement_great_capacity = "CgkIg7eIzcIOEAIQFA"; // <GPGSID>
        public const string achievement_great_intelligent = "CgkIg7eIzcIOEAIQEQ"; // <GPGSID>
        public const string achievement_einstein = "CgkIg7eIzcIOEAIQGQ"; // <GPGSID>
        public const string achievement_encyclopedia = "CgkIg7eIzcIOEAIQHg"; // <GPGSID>

}

